### ISSUE TITLE
dead link: RFA_versus_FFT_for_heartrate.zip

### ISSUE THREAD

**Issue by beta-tester** [har-in-air/ESP8266_SPO2_PULSE_LOGGER#1]
hi,
in your README text you link to a file that doersx not exist
https://github.com/har-in-air/ESP8266_SPO2_PULSE_LOGGER/blob/master/RFA_versus_FFT_for_heartrate.zip

**Comment by beta-tester** [comment]
just found the file under tag v0.9
https://github.com/har-in-air/ESP8266_SPO2_PULSE_LOGGER/blob/v0%2C9/RFA_versus_FFT_for_heartrate.zip

**Comment by har-in-air** [comment]
Link to FFT archive in README fixed
